### ISSUE TITLE
Suggesting Edit: Hello World Tutorial

### ISSUE THREAD

**Issue by friedger** [holochain/docs-pages#185] opened 2020-02-09 16:25 UTC
Page URL: http://developer.holochain.org/docs/tutorials/coreconcepts/hello_world/

At the end when opening Terminal 3, the agent is called again `Alice` instead of `Bob`

**Comment by mitra42** [comment] 2020-02-17 01:21
Seems to be related to https://github.com/holochain/docs-pages/issues/187 which has a suggested fix to the bug

**Comment by pdaoust** [comment] 2020-02-19 20:43
Closing as a duplicate of #187.

**Closed** 2020-02-19 20:44 UTC
Labels: duplicate
