### ISSUE TITLE
Suggesting Edit: Hello World Tutorial

### ISSUE THREAD

**Issue by mitra42** [holochain/docs-pages#191] opened 2020-02-17 01:08 UTC
Page URL: http://developer.holochain.org/docs/tutorials/coreconcepts/hello_world/

There is a line under `Tab Bob` that says `Go to 127.0.0.1:8889` 
This fails.

Its unclear if I'm doing something wrong, or this is a typo and should also be `Go to 127.0.0.1:8888` like the tab above.

**Comment by mitra42** [comment] 2020-02-17 01:15
Its also unclear - if they are both on port 8888 that the two agents are distinct ? i.e. how is `Tab Bob` connecting to the Bob instance and `Tab Alice` conncted to the Alice instance.

**Comment by mitra42** [comment] 2020-02-17 01:19
I think this is related to the bug posted in https://github.com/holochain/docs-pages/issues/187 a week ago.

**Comment by zippy** [comment] 2020-02-18 02:07
Hi @mitra42 Thanks for the edits and the corrections.  We definitely need to get these things straightened out and we are bit behind.  Thank you for your patience.

**Comment by pdaoust** [comment] 2020-02-19 20:46
Hey @mitra42 yes, thank you for taking the time to get picky -- it's what we need, and haven't had the chance to do yet after the org reset. Closing as a duplicate of #187.

**Closed by pdaoust** 2020-02-19 20:46 UTC
