### ISSUE TITLE
Suggesting Edit: Hello Me Tutorial - discrepancy in first UI hello.js text box

### ISSUE THREAD

**Issue by mitra42** [holochain/docs-pages#154] opened 2019-12-15 10:38 UTC
Page URL: http://developer.holochain.org/docs/tutorials/coreconcepts/hello_me/

Oops - in the UI section the "Check your code" for hello.js bears almost no relationship to the code you had us type in above - there are a bunch of different functions, and even what is there has some changed syntax. 

Has anyone tested the tutorials - I keep finding bugs in them ....

**Comment by mitra42** [comment] 2019-12-16 04:08
See discussion in https://forum.holochain.org/t/potential-bug-in-hello-me-tutorial/1265/9

**Comment by dhtnetwork** [comment] 2019-12-17 04:37
> Has anyone tested the tutorials - I keep finding bugs in them ....

Hi @mitra42 thank you for taking the time to check out the tutorials. The tutorials have helped a lot of people learn Holochain and developer their first app.  We always appreciate input from the community and seek to improve the effectiveness of our docs.

The tutorials are viewed and tested. But please note that there could be a number of things that could impact your experience with the tutorials.

Can you describe the issue? 
Can you provide a screenshot of the bug?
Can you clarify what this means? ---? "I keep finding bugs in them" Have you reported all the bugs? in a clear and reproduceable matter? If so, can you provide your findings.

Learning Holochain is a wonderful journey and the more info you can share about your experience level and details about issues/bugs the better can we can help.

Are there specific changes you would like to post?  Please let us know otherwise, we'll take a look at Hello Me again and may need to close out this issue if there are specific issues reported.

Regards, dhtnetwork.  @mitra42

**Comment by dhtnetwork** [comment] 2019-12-17 04:40
We do monitor the Forum and Github. So it's sufficient to simply submit an issue on GitHub. We'll review and do what we can to address. 

Also, I'm curious if you have explored the other tutorials? Or was Hello Me the first tutorial you tried?

**Comment by mitra42** [comment] 2019-12-17 08:31
Hi @dhtnetwork - 
* Yes - I have done all tutorials up to Hello Me, there were a number of typos in previous tutorials, but the mistakes were obvious and fixable up until this point. 
* I posted this bug and #153 specifically, I thought both were clear, and I think @freesig has confirmed them. 
* I thought the opening comment was clear .... but to make it clearer

#### STR
- On https://developer.holochain.org/docs/tutorials/coreconcepts/hello_me/
- Scroll to the heading `UI`
- follow the steps below to create hello.js until you get to `check your code`
- open that drop down
- compare code shown with what you just created
- notice they bear little resemblance to each other, for example the code to `check` contains a function `show_posts` which will not be in the code you created in the steps above. 
- this is where I gave up, because the previous bug - reported in #153 had already wasted an hour to figure out the typo in the tutorial, and it was clear the rest of the turtorial hadn't been checked either.

**Comment by dhtnetwork** [comment] 2019-12-17 15:00
@mitra42 Hi, excellent thank you for provide the additional information. These tutorials have been released with the caveat that they are work in progress.  But moving forward, it seems like some of the tutorials or all can simply go through an editorial and additional test review before we publish.

I appreciate your attention to detail and quality.

**Comment by freesig** [comment] 2020-02-25 23:49
Is this still relevant since all the "check your code" is now generated?

**Comment by mitra42** [comment] 2020-02-25 23:59
I don't know @freesig - each time I posted a bug someone said the Check-your-code boxes were auto-generated, but the bugs were obviously there (as in the STR above), so maybe the process has changed, but the large number of recently posted bugs in the Hello_World suggested otherwise, i.e. the code produced in the tutorial couldn't possible work as it had typos in it. 

The approach I took was to follow the tutorial step by step, check it into my local git repo, then cut and paste the "Check your code" over it, non-trivial differences were how I found these bugs, maybe someone (maybe someone new) on your team needs to run through the tutorials step by step and actually check that the code matches, and that the code runs as specified ?

**Comment by pdaoust** [comment] 2020-03-06 23:19
I've done a manual sanity check, starting at the code in HelloGui and moving to the end of HelloMe. I haven't found any discrepancies between my typed code and the 'Check Your Code' boxes, so I'm thinking it was some bugs in the tutorial parser/compiler that have been fixed. Closing until I'm proven wrong! :)

**Closed by pdaoust** 2020-03-06 23:19 UTC
