### ISSUE TITLE
Suggesting Edit: Hello World Tutorial

### ISSUE THREAD

**Issue by mitra42** [holochain/docs-pages#189] opened 2020-02-17 00:58 UTC
Page URL: http://developer.holochain.org/docs/tutorials/coreconcepts/hello_world/

I think - but I'm not sure that the second  place it says `hc run --networked sim2h --agent-name Alice` you mean `hc run --networked sim2h --agent-name Bob`

**Comment by mitra42** [comment] 2020-02-17 01:21
Actually .... this might be related to https://github.com/holochain/docs-pages/issues/187 which makes a different suggestion how to fix this bug ...

**Comment by freesig** [comment] 2020-02-18 02:12
Yes this should be Bob sorry, I'll fix that, feel free to open a PR to develop

**Comment by pdaoust** [comment] 2020-02-19 20:47
Closing as a duplicate of #187 , which has a complete solution (distinct port number from Alice's instance).

**Closed** 2020-02-19 23:22 UTC
Labels: duplicate
